#!/usr/bin/env node

const fs = require('fs');
const PdfPrinter = require('pdfmake');
const fonts = require('./font-config').fonts;
var printer = new PdfPrinter(fonts);

const inFn = process.argv[2];
const outFn = inFn + ".pdf";

const rawData = fs.readFileSync(process.argv[2], null);
const text = rawData.toString('base64');

const dnow = new Date();

var docDefinition = {
  info: {
    title: 'Paperback Backup ' + dnow.toISOString(),
  },

  pageSize: 'LETTER',

  content: [
    'Your Paperback Backup',
    'PAGE 1 of 1',
    { qr: text, eccLevel: 'M' },
  ],

  defaultStyle: {
    font: 'Helvetica'
  }
};

var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream(outFn));
pdfDoc.end();

